name: Cloud Build

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allows manual or programmatic triggering

jobs:
  build:
    runs-on: ubuntu-latest # Use GitHub-hosted runner

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3 # Fetches repository code
    
# Comment following debug lines     
  #    - name: Verify Current Directory
   #     run: pwd

    #  - name: List Files
   #     run: ls -al

    #  - name: Verify .NET Installation
   #     run: dotnet --info
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'  # Use your preferred Python version

      - name: Install dependencies
        run: |
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Execute CI Pipeline Logic
        run: python ci_pipeline.py  # Replace with your Python script filename
